### 230501

- 얕은 복사 및 깊은 복사

In [116]:
a = [6,7,8,9,10]

In [117]:
#b입니다.
b = [1,2,3,4,5]

# 1.
## 2.
### 3.

In [118]:
3 and 4

4

In [119]:
3 & 4 # &: 논리연산자가 X -> 비트연산자.
#0011  & 0100 -> 0000

0

In [120]:
3 or 4

3

In [121]:
3 | 4

7

- 연습문제 5-1

In [122]:
a =34
b =4 

r = a%b

if r>3:
    print('실패')
elif r==3:
    print('무승부')
else :
    print('성공')

성공


- 연습문제 5-3

In [123]:
birth_year = int(input('당신의 태어난 년도를 입력해주세요.'))

age = 2023 - birth_year+1

message = ""
if 20<=age and age<=26:
    message="대학생"
elif 17<=age and age<20:
    message="고등학생"
elif 14<=age and age<17:
    message="중학생"
elif 8<=age and age<14:
    message="초등학생"
else:
    print('학생이 아닙니다.')
print(message)   

ValueError: invalid literal for int() with base 10: ''

- 연습문제 5-5 


In [ ]:
num = int(input('정수를 하나 입력하세요.'))

if num %2==0:
    if num%3==0:
        print('2와 3으로 나누어 집니다.')
    else : 
        print('2로 나누어집니다.')
elif num %3==0:
    print('3으로 나누어 집니다.')
else:
    print('어느 것으로도 나누어지지 않습니다.')

2로 나누어집니다.


- P.187) Toy example
    - 1부터 10까지의 합을 구하시오.(range 함수를 이용하시오.)

In [ ]:
sum=0
for i in range(1,11):
    sum = sum+i
print(sum)

55


P.189) 연습문제2)

(1) 계단형

In [ ]:
n = int(input('n:'))
for i in range(n):
    print(' '*i,end='') #end의 역할 sep와 비슷한 기능(구분자 사용) 
    print('*'*n)

***
 ***
  ***


(2) 삼각형

In [ ]:
n = int(input('n:'))
for i in range(1,n+1):
    print('*'*i)

ValueError: invalid literal for int() with base 10: '*'

(2)-1

In [ ]:
n = int(input('n:'))
for i in range(1,n+1):
    print(' '*(n-i), end='')
    print('*'*i)

                             *
                            **
                           ***
                          ****
                         *****
                        ******
                       *******
                      ********
                     *********
                    **********
                   ***********
                  ************
                 *************
                **************
               ***************
              ****************
             *****************
            ******************
           *******************
          ********************
         *********************
        **********************
       ***********************
      ************************
     *************************
    **************************
   ***************************
  ****************************
 *****************************
******************************


(3) 역삼각형

In [ ]:
n = int(input('n:'))
for i in range(n):
    print('*'*(n-i))

ValueError: invalid literal for int() with base 10: ''

(3-1)

In [ ]:
n = int(input('n:'))
for i in range(n):
    print(' '*i, end='')
    print('*'*(n-i))

(4) 피라미드

In [ ]:
n = int(input('n:'))
for i in range(1,n+1):
    print(' '*(n-i), end='')
    print('*'*(2*i-1))

                                       *
                                      ***
                                     *****
                                    *******
                                   *********
                                  ***********
                                 *************
                                ***************
                               *****************
                              *******************
                             *********************
                            ***********************
                           *************************
                          ***************************
                         *****************************
                        *******************************
                       *********************************
                      ***********************************
                     *************************************
                    ******************************

P.190) 연습문제 3

In [ ]:
#(1)
x = [3,6,9,20,-7,5]

In [ ]:
for i in x:
    print(i*10)

30
60
90
200
-70
50


In [ ]:
#심화
for i in range(0,len(x)):
    x[i] = x[i]*10
print(x)

[30, 60, 90, 200, -70, 50]


In [ ]:
#(2)
y = {'math':70, 'Science':80, 'english':20}

In [ ]:
for key in y:
    val = y[key]
    y[key] = y[key]+10
    print('%s : %d' %(key,val+10)) 

math : 80
Science : 90
english : 30


P.191) 연습문제4

In [ ]:
import random
true_value = random.randint(1,100)
input_value = 99999 #임의의 값 활당.
print('숫자를 맞춰보세요.')
while true_value !=input_value:
    input_value = int(input())
    if input_value>true_value: #사용자의 입력값이 true_value 클때
        print('숫자가 너무 큽니다.') 
    else: 
        print('숫자가 너무 작습니다.') #사용자의 입력값이 true_value보다 작을 때,
print(f'정답입니다.입력한 숫자는 {true_value}입니다.')

숫자를 맞춰보세요.


ValueError: invalid literal for int() with base 10: ''

P.192) 연습문제 5번

In [ ]:
word = ['school','game','piano','science','hotel','mountain']

In [ ]:
len(word)

In [ ]:
a = list()
for i in range(len(word)):
    if len(word[i])>=6:
        a.append(word[i])
print(a)

P.193) 연습문제6

In [ ]:
b = int(input('정수를 입력하세요.'))
if b<=0:
    print('음수는 정의하지 않음.')
else:    
    for a in range(1,b+1):
        if a%3==0 and a%5==0: 
            print('3과 5의 공배수')
        elif a%3==0:
            print('3의 배수')
        elif a%5==0:
            print('5의 배수')
        elif 1<=a<=100:
            print(a)
        else:
            print('1과 100사이 숫자가 아닙니다.')

 P.194 연습문제7

In [ ]:
c=0

d=1

while (d==1):
    a = (input())
    if (a=='s'or a=='S'):
        d=0
    else:
        a = int(a)
        c+=a
print(c)


P.195 연습문제8

In [ ]:
kor_score = [39,69,29,100,80]
math_score = [32,59,85,30,90]
eng_score = [49,70,48,60,100]

mideterm_score = [kor_score, math_score,eng_score]

In [ ]:
student_score = [0,0,0,0,0]
i=0
for subject in mideterm_score: #kor,math,eng 과목 선택
    for score in subject: #과목 선택후
        student_score[i]+=score #각 학생마다 개별로 교과 점수를 저장
        # print(subject,score,'i:',i,student_score) #kor->math->eng 
        i+=1 #학생 index 구분
    i=0 # 과목이 바뀔 때 학생 인덱스
else:
    a,b,c,d,e = student_score  #학생별 점수를 unpacking
    student_average = [a/3,b/3,c/3,d/3,e/3]
    print(student_average)



In [ ]:
print('나눗셈을 진행합니다. {:.20f}'.format(1/3))

P.225) 연습문제

In [ ]:
def div3(a,b):
    if a<b:
        big=b
        small=a
    elif b<=a:
        big=a
        small=b
    else:
        print('정수가 아닙니다.')
    if small==0:
        print('0은 사용할 수 없습니다.')
    elif abs(big)<0 or abs(small)<0:
        print('정수를 입력해주세요.')
    else:
        q = big//small
        r = big%small
        return (q,r)

P.229) 연습문제

In [ ]:
def func(string, unit=2):
    i=0
    while i<len(string):
        print(string[i:i+unit])
        i +=unit

In [ ]:
func('테스트를 위한 문장입니다.')

In [ ]:
func('테스트를 위한 문장입니다.',4)

- 참고 : https://mingrammer.com/understanding-the-asterisk-of-python/

In [ ]:
def test(*args):
    print(args)

In [ ]:
def test(*a):
    print(*a)

In [ ]:
test(1,2,3,4,5,6,7,8,9,10)

In [ ]:
test([1,2],3)

In [ ]:
test([1,2])

In [ ]:
def test2(**kwargs):
    print(kwargs)

In [ ]:
test2(a=1,b=2,c=3)

P.230

In [ ]:
def add_all(*inputs):
    s=0
    for i in range(len(inputs)):
        s +=inputs[i]
    return s

- TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [ ]:
def add_all2(*inputs):
    return sum(inputs)

In [ ]:
add_all([1,2,3,4,5,6,7,8,9,10])

In [ ]:
def add_all3(*args):
    s=0
    for i in args:
        for j in i:
            s +=j
        return s

In [ ]:
add_all3([1,2,3,4,5,6,7,8,9,10])

In [ ]:
add_all3([1,2,3,4,5,6,7,8,9,10])

In [ ]:
add_all3(1,2,3,4,5,6,7,8,9,10)

In [ ]:
def add_all4(*args):
    temp=0
    for i in range(len(args)):
        if type(args[i]) == list:
            for j in args[i]:
                temp +=j
        else :
            temp +=args[i]
    return temp

In [ ]:
add_all4([1,2,3,4,5,6,7,8,9,10])

In [ ]:
add_all4(1,2,3,4,5,6,7,8,9,10)

P.239

In [ ]:
#재귀적으로 하지 않은 것.
def fact(n):
    f=1 #곱을 계산할 변수의 초깃값
    for i in range(1,n+1): #1부터 n까지 반복
        f = f*i #곱셈연산
    return f

In [ ]:
#재귀적으로 하는 것.
def fact(n):
    if n<=1: #n이 1이하이면 종료조건
        return 1
    return n*fact(n-1)

In [ ]:
fact(5)

- 참고 : https://velog.io/@joo4438/python-%ED%8C%A9%ED%86%A0%EB%A6%AC%EC%96%BC-%EA%B5%AC%ED%95%98%EA%B8%B0%EC%9E%AC%EA%B7%80

P.242

In [ ]:
people = ['펭수','뽀로로','뚝딱이','텔레토비']

def func1(line):
    new_lines = []
    i=1 #대기번호를 트래킹하는 변수 i
    for x in line:
        print('대기번호 %d번 : %s' %(i,x))
        new_lines.append((i,x))
        i +=1 #별도로 업데이트를 해줘야 함.
    return new_lines

In [ ]:
lines = func1(people)

- enumerate(열거하다)
    - 반복 가능한 객체의 인덱스와 원소에 함께 접근할 수 있는 함수.

In [ ]:
lst = ['a','b','c']
for x in enumerate(lst):
    print(x)

In [ ]:
lst1 = 'abcd'
for x in enumerate(lst1):
    print(x)

In [ ]:
people = ['펭수','뽀로로','뚝딱이','텔레토비']

def func1(line):
    new_lines = []
    for idx,val in enumerate(line):
        print('대기번호 %d번 : %s' %(idx,val))
        new_lines.append((idx+1,val))
    return new_lines

- zip
    - 반복가능한 객체들을(2개 이상) 병렬적으로 묶어주는 함수.
    - 각 원소들을 튜플의 형식으로 묶어줌.

In [ ]:
str_list = ['one','two','three','four']
num_list = [1,2,3,4]

for i in zip(num_list,str_list):
    print(i)

P.251

In [ ]:
items = [1,24,3,6,7]

In [ ]:
str_items = list(map(lambda x:str(x),items))
print(str_items)

- list comprehension

- 0~9까지를 순서대로 가지고 있는 리스트를 만드세요.

In [ ]:
#1.
list_1 = [0,1,2,3,4,5,6,7,8,9]
#2.
list_2 = []
for x in range(10):
    list_2.append(x)
print(list_2)

In [ ]:
lc_1 = [x for x in range(10)]
print(lc_1)

P.255

    - for 문

In [ ]:
#1) 구구단 2단
tables = [2 *x for x in range(1,10)]
print(tables)

In [ ]:
#2) 코로나 바이러스
sentence = '코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다. 외출 시에는 마스크를 끼고, 손씻기를 생활화합시다.'

In [ ]:
len_sent = [len(s) for s in sentence.split()]
print(len_sent)

P.258

    - for 문+if 문

- 10부터 20까지의 숫자들 중에서 짝수만을 담은 리스트를 만들어보자!

In [ ]:
list3 = []
for x in range(10,21):
    if x%2==0:
        list3.append(x)
print(list3)

In [ ]:
lc_2 = [x for x in range(10,21) if x%2==0]
print(lc_2)

P.258

In [ ]:
#1)
lc_3 = [x**2 for x in range(1,11) if x**2<50]
print(lc_3)

In [ ]:
lc_4 = [s for s in sentence.split() if len(s) <5]
print(lc_4)

- for+if+else

- 1부터 10까지의 숫자들 중 홀수 이면 어떤 제곱수를, 짝수이면 세제곱수를 담은 리스트를 만들어보자.

In [ ]:
list_4 = []
for x in range(1,11):
    if x%2==1:
        list_4.append(x**2)
    else :
        list_4.append(x**3)

In [ ]:
[x**2 if x%2==0 else x**3 for x in range(1,11)]

- for문+for문

In [ ]:
word1 = 'hello'
word2 = 'world'

result = [i+j for i in word1 for j in word2]
result

 P.261

In [ ]:
list_5 = [12,67,32,48,19,57,29,49]
lc_6 = [x+5 if x<=40 else 41 for x in list_5]
lc_6

In [ ]:
students = {"보라돌이":61, "뚜비":35, "나나":78,"뽀":88}

result = [(name,True) if score>60 else (name, False) for name,score in students.items()]
result

In [ ]:
import numpy as np

n=1000000
numpy_arr = np.arange(n)
python_list = list(range(n))

In [ ]:
import time
start = time.time() #시작시간 저장
python_list = [x**3+10 for x in python_list]
print('time:', time.time() - start) #현재시각-시작시간 = 실행시간

In [ ]:
%%time
numpy_arr = numpy_arr**3+10

In [ ]:
A = [1,2,3,4]

a = np.array(A)
print(type(a))
print(a)

- 벡터화
    - 배열은 for문을 작성하지 않고 데이터를 일괄처리 하는 것.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
arr+arr

In [ ]:
arr/arr

- 브로드캐스팅
    - 다른 모양의 배열 간의 산술 연산을 수행할 수 있도록 해주는 numpy의 기능.

In [ ]:
arr

In [ ]:
10 - arr

In [ ]:
arr*3

In [ ]:
arr/3

In [ ]:
arr2 = np.array([100,200,300])

In [ ]:
arr4 = np.array([[100],[200]])
arr4

In [ ]:
arr+arr4

In [ ]:
arr3 = np.array([100,200])

In [ ]:
arr+arr3

In [ ]:
arr+arr2

In [ ]:
list_1 = [1,2,3]

In [ ]:
list_1+list_1

In [ ]:
arr_1 = np.array([1,2,3])
arr_1+arr_1

ndim
- 배열의 차원의 갯수

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [129]:
# 0차원 (상수)
import numpy as np
a = np.array(10)
print(a)
print(a.ndim)

10
0


In [130]:
# 1차원
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [131]:
# 3차원
a = np.array([[[[1,2],[3,4]]]])
print(a)
print(a.ndim)
print(a.shape)

[[[[1 2]
   [3 4]]]]
4
(1, 1, 2, 2)


range 함수를 이용

In [132]:
arr1 = np.array(range(20))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
# zeros 
np.zeros(5) # 0 이 할당 된 것

array([0., 0., 0., 0., 0.])

In [135]:
# ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
np.full((4),(5))

array([5, 5, 5, 5])

In [137]:
np.empty((2,3), dtype=np.float32)

array([[8.4e-45, 9.8e-45, 1.1e-44],
       [1.3e-44, 1.4e-44, 1.5e-44]], dtype=float32)

In [138]:
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [139]:
np.arange(3,50,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [140]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

- 배열 결합 함수.  
 - hstack, concatenate(axis=0) 0=행을 인식
 - 두 배열을 왼쪽에서 오른쪽으로 붙이기. 

In [141]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [142]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [143]:
np.concatenate([a,b],axis=0)

array([1, 2, 3, 4, 5, 6])

In [144]:
np.stack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [146]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
np.concatenate((a,b), axis=1) # 10 vector는 안됨

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
c = np.array([[0,1,2],[4,5,6]])
d = np.array([[6,7,8],[9,10,11]])
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

두 배열을 위 아래로 붙이기.

In [148]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [150]:
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [151]:
import random
import numpy as np
random.random() # 0<= 리턴 값 <=1

0.04349334202653066

In [155]:
data=[1,2,3,4,5,6,7]
np.random.choice(data,3)

array([7, 2, 7])

In [157]:
data= ['apple', 'banana', 'grape', 'orange']
random.choice(data)

'orange'

- seed
  - 난수 초기값 부여 -> 재현 가능성(Reporducibility) 

In [164]:
np.random.seed(42)

In [163]:
np.random.rand(100)

array([0.43088752, 0.24871427, 0.61714499, 0.70677722, 0.16704191,
       0.16761922, 0.03667143, 0.73640202, 0.66380453, 0.47463088,
       0.84417045, 0.80567015, 0.58535436, 0.86827128, 0.20584121,
       0.11191962, 0.26974961, 0.05708686, 0.53116953, 0.93660569,
       0.03934354, 0.12210991, 0.45219903, 0.93387502, 0.3161561 ,
       0.50723481, 0.04157286, 0.1483432 , 0.98663012, 0.9651187 ,
       0.00493998, 0.95181179, 0.63911994, 0.86791829, 0.45473986,
       0.51559603, 0.48884658, 0.66686426, 0.13965125, 0.02997359,
       0.30792994, 0.70468076, 0.20185345, 0.67343243, 0.96991205,
       0.09390072, 0.67260212, 0.44375022, 0.86814225, 0.17714979,
       0.69262595, 0.83811529, 0.94461422, 0.68324803, 0.49717476,
       0.61784724, 0.86890498, 0.57060975, 0.03038706, 0.9309487 ,
       0.68952675, 0.67651339, 0.21567515, 0.65888547, 0.39386441,
       0.65123298, 0.10659303, 0.6578453 , 0.99941373, 0.04821204,
       0.97717418, 0.40690796, 0.87075345, 0.78238548, 0.56701

In [162]:
np.random.randn(1000) # 정규분포

array([ 8.70470682e-02, -2.99007350e-01,  9.17607765e-02, -1.98756891e+00,
       -2.19671888e-01,  3.57112572e-01,  1.47789404e+00, -5.18270218e-01,
       -8.08493603e-01, -5.01757044e-01,  9.15402118e-01,  3.28751110e-01,
       -5.29760204e-01,  5.13267433e-01,  9.70775493e-02,  9.68644991e-01,
       -7.02053094e-01, -3.27662147e-01, -3.92108153e-01, -1.46351495e+00,
        2.96120277e-01,  2.61055272e-01,  5.11345664e-03, -2.34587133e-01,
       -1.41537074e+00, -4.20645323e-01, -3.42714517e-01, -8.02277269e-01,
       -1.61285712e-01,  4.04050857e-01,  1.88618590e+00,  1.74577813e-01,
        2.57550391e-01, -7.44459158e-02, -1.91877122e+00, -2.65138754e-02,
        6.02302099e-02,  2.46324211e+00, -1.92360965e-01,  3.01547342e-01,
       -3.47117697e-02, -1.16867804e+00,  1.14282281e+00,  7.51933033e-01,
        7.91031947e-01, -9.09387455e-01,  1.40279431e+00, -1.40185106e+00,
        5.86857094e-01,  2.19045563e+00, -9.90536325e-01, -5.66297730e-01,
        9.96513651e-02, -

로도 번호 생성기를 만드세요.
 로또 번호를 몇개 생성할까요? > 4
 1. 로또번호 : [13 16 20 22 27 43]
 2. 로또번호 : [21 27 31 36 37 45]
 3. 로또번호 : [ 4 15 16 26 30 39]
 4. 로또번호 : [ 7 15 26 29 40 41]

- 로또 번호 생성기

In [196]:
import numpy as np
def make_lotto(count):
    for i in range(count):
        lotto_num = [] #로또 번호가 담길 리스트형 변수
        for j in range(6): #6번 반복
            lotto_num = np.random.choice(range(1,46),6,replace=False)
            # replace=False 중복 추출 막기
            lotto_num.sort() #값 정렬
        print('{}.로또번호:{}'.format(i+1,lotto_num))
count = int(input('로또 번호를 몇개 생성할까요?'))
make_lotto(count)