add_all 함수를 짜봅시다

In [31]:
def add_all(*args):
    a=0
    for i in range(len(args)):
        a +=args[i]
    return a
add_all(1,2,3,4,5,6,7,8,9,10)

55

In [32]:
def add_all4(*args):  # args 튜플을 리스트로 받는 법
    temp = 0
    for i in range(len(args)) :
        if type(args[i]) == list:
            for j in args[i] :
                temp += j
        else :
            temp += args[i]
    return temp

55


In [33]:
add_all4([1,2,3,4,5,6,7,8,9,10]) # 리스트

55

In [34]:
add_all4(1,2,3,4,5,6,7,8,9,10) # 튜플

55

numpy 
- 산술계산용 라이브러리
- n 차원의 다양한 객체 
array 각각이 오브젝트 (자유로움)

In [37]:
import numpy as np
print(np.__version__)

1.24.3


In [39]:
import numpy as np
A = [1,2,3,4,]
a = np.array(A)
s = a[:2]
print('A의 출력입니다.%a'%a)
print('S의 출력입니다.%s'%s)

A의 출력입니다.array([1, 2, 3, 4])
S의 출력입니다.[1 2]


- Ndarray 타입을 검색하거나 슬라이싱은 참조만 할당하므로  
변경을 방지하기 위해서는 새로운 ndarray로 만들어 사용 .copy 메소드가 필요

In [40]:
ss = a[:2].copy()
print(ss.size)
ss[0]=99
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1 2]
[99  2]


In [41]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]
